### ISSUE TITLE
Wissenschaftliches Paper (15P)

### ISSUE THREAD

**Issue by mhoellner** [mhoellner/ELearning#21]
wissenschaftliches Paper (15P)
- 7 bis 10 Seiten
- two-column IEEE style
- Thema: "Phasen, Techniken und Strategien der Softwareentwicklung anhand eines Kursprojekts im Modul SWE-II"

Siehe [mhoellner/SWE-Paper](https://www.github.com/mhoellner/SWE-Paper)

**Comment by Prohli** [comment]
Analyse Phase (MAX)
    -  Zusammenfassung der Analysephase Semester 3.
     - Umfrage mit Auswertung der Ergebnisse 

Implementierung 
    - Frontend Implementierung  (Katja)
    - Backend Implementierung (Milan)
Testphase
    - Blackbox Test durch Nicht Entwickler (Max und Katja)

**Comment by Prohli** [comment]
Entwurf der Benutzerschnistellen Nach ISO FURZI Sommervile (Max) 
Entwurf Backend Klassenmodell

**Comment by mhoellner** [comment]
Abgegeben.
