### ISSUE TITLE
Connection to OpenXchange-Server

### ISSUE THREAD

**Issue by mhoellner** [mhoellner/ELearning#6]
From a login form, use the credentials with the API to see, if these are valid.

**Comment by katjaholzinger** [comment]
Also, die URL für den Login lautet:

https://webmail.stud.hwr-berlin.de/ajax/login?action=login

An diese Adresse müsst ihr per POST-Method die Variablen "name" und "password" übergeben. Wenn die Daten richtig sind, bekommt ihr vom OX-Server eine Session-ID zurück, wenn nicht eine Fehlermeldung. 

Ihr könnt mit der Chrome-Erweiterung "Postman" die Funktionalität testen.

Ich habe in meinem PHP-Script eine CURL-Abrage auf diese URL gemacht und speichere mir die Session-ID und die Benutzer-ID zwischen, um den Klarnamen abzufragen. Dazu die API

https://webmail.stud.hwr-berlin.de/ajax/contacts?action=getuser

nutzen. Hier müssen bei "session" die Session-ID und bei "id" die Benutzer-ID übergeben werden. Achtung: Die API braucht aktive Cookies.

Unter http://oxpedia.org/wiki/index.php?title=HTTP_API#Login kann alles nochmal nachgelesen werden.

**Comment by mhoellner** [comment]
Hey @Prohli,
hier geht es erst mal um ein Formular aus dem du die eingetragenen Werte an die API weiterleitest und damit testest, ob diese gültig sind.

**Comment by Prohli** [comment]
Hab jetzt mal eine kurze und knappe Lösung.. weiß grad aber nicht so recht ob das so ist wie du/ihr euch das vorstellt^^.

Donnerstar haben wir ja eine sehr lange Pause, vielleicht haben wir da ein wenig Zeit?!
